version: "3.2"
services:
 redis:
    image: "redis:alpine"

    command: redis-server --requirepass 0072D094F534CABECFDAE6FEC02456B3CB9B3D099CA601A25F144AFD4ADCC17080A42A4837CCF9E4301190EACAF2B36978D0B1D2414F3D945E702AE381AB103E

    volumes:
     - $PWD/.docker/redis-data:/var/lib/redis
     - $PWD/.docker/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

    network_mode: "host"
